### PR TITLE
Initial schema and build

### PR DESCRIPTION
**Pull request by isedwards**
Initial schema as JSON and deploy script from @david-i-berry

### CODE REVIEW

**Comment by isedwards** [comment]
@david-i-berry  I'm not sure about a couple of things:
1. The JSON appears to be a custom format and it looks like the intention is to create and maintain our own custom tooling to create UML and SQLAlchemy models from this? Instead I was expecting either:
    - JSON schema files and reusing some existing tooling. For example, [this tool](https://www.npmjs.com/package/sql-ddl-to-json-schema) converts from DDL to JSON schema (but not the other way around). Or ...
    - Definition and maintenance of the physical data model using SQLAlchemy models (but only if these models were the single source of truth)
2. The Climate Data Model Standard is intended to be project agnostic. I'm not sure OpenCDMS is the correct home for the single source of truth. Would it make more sense for the versioned data model definition to live at wmo-im/cdm?

**Comment by david-i-berry** [comment]
@isedwards 

(2) I agree, the correct home will be in the TT-CDM and documented in the relevant manual. Our task in the TT-CDM will be to develop and document the logical data model. Here we will implement that data model. 

(1) is slightly more complicated. I've looked at various tools and started off in json schema (after EA that I was trying to avoid) but then I struggled to generate UML diagrams from the json schema. I also looked at starting from PlantUML files but there doesn't appear to be any easy solution there.  At the moment I've used the json file I shared and two short jinja2 templates (~30 lines each) to create the models.py and a UML diagram but I'm not sure this is the correct way to go.  

Ultimately I think we'll need to bite the bullet and use EA which makes collaboration more difficult and will require the use of EA to generate the DDL. 

At the moment I think we can have the models.py as part of this repository, I'm not sure about the JSON, partly why I haven't pushed yet. I also have documentation that I'm going to push.

**Comment by david-i-berry** [comment]
I've attached an example json schema (in YAML) with the objects flattened / un nested. This still needs work but may be a starting point to if we to use jsonschema to define the model. 

[physical-data-model.txt](https://github.com/opencdms/opencdms-data-layer/files/10259394/physical-data-model.txt)

**Comment by faysal-ishtiaq** [comment]
I added some additional files to automate the process to try it out. I am pasting the contents of the files here.

<details>
<summary>Dockerfile</summary>

```dockerfile
FROM python:3.10-slim

RUN apt-get update -y
RUN apt-get install -y python3-dev libpq-dev build-essential

COPY requirements.txt /opt/project/requirements.txt

RUN pip install -r /opt/project/requirements.txt

WORKDIR /opt/project
ENV PYTHONPATH="$PYTHONPATH":/opt/project

```
</details>

<details>
<summary>docker-compose.yml</summary>

```yaml
version: "3"

services:
  opencdms-database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  db-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "${PWD}:/opt/project"
    entrypoint: bash
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

```
</details>


<details>
<summary>requirements.txt</summary>

```text
sqlalchemy
SQLAlchemy-Utils
geoalchemy2
psycopg2

```

</details>

And then when I run the script like below, it throws error.

```bash
$ docker-compose up --build -d
$ docker-compose run db-builder
root@fde5a57a4fbc:/opt/project# python build_db.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.ObjectInUse: cannot drop the currently open database
``` 

when I comment line 19 and 20, it returns throws `psycopg2.errors.DuplicateDatabase: database "postgres" already exists`

When I comment line 21, it doesn't throw any error. But there are no databases either.

When I changed `build_db.py` like below

```python
import os
from sqlalchemy import create_engine, schema

from data_model import Base

UID = os.environ["POSTGRES_USER"]
PWD = os.environ["POSTGRES_PASSWORD"]
DBNAME = os.environ["POSTGRES_DB"]

engine = create_engine(f"postgresql+psycopg2://{UID}:{PWD}@opencdms-database:5432/{DBNAME}")

Base.metadata.bind = engine

schemas = {v.schema for k, v in Base.metadata.tables.items()}

for _schema in schemas:
    if not engine.dialect.has_schema(engine, _schema):
        engine.execute(schema.CreateSchema(_schema))

Base.metadata.create_all(engine)

```

and changed the docker image for db to `postgis/postgis:13-3.3`, it worked.

image

**Pull request merged**
