### PR TITLE
Exploring oso

### PR DESCRIPTION
**Pull request by chinedu117**
This PR tries to implement the RBAC for sqlalchemy models as described in https://github.com/opencdms/pyopencdms/issues/81

Steps to test:

docker-compose up -d
docker-compose run db-builder
pytest

In order to avoid sqlalchemy.orm.exc.DetachedInstanceError, the stations relationship on the Users model must be eager-loaded not lazy-loaded. This is because the db session object used for user authentication is different from the authorized_session created by oso. Hence the session may be invalidated by the time oso tries to load the stations relationship.

### CODE REVIEW

**Review by isedwards — COMMENTED** [review]
@chinedu117 

When I run `docker-compose run db-builder` I end up inside the `postgis/postgis:13-3.3` container as `root`.

If I then run `pytest` I get the following error for each test:
```
E       sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) schema "cdm" does not exist
```

I've tried the usual checks to see it postgres is running but not much seems to be installed - it's a very minimal environment and I'm having trouble debugging.

Any suggestions?

**Comment by chinedu117** [comment]
@isedwards 

Thanks for pointing it out. Its fixed now.

**Review by isedwards — CHANGES_REQUESTED** [review]
@chinedu117 - could you add some developer docs that gives an example of accessing the station table using standard SQLAlchemy commands - and then an equivalent example that shows the outcome if you use the `authorized_session` and `sqlalchemy_oso`?

**Comment by isedwards** [comment]
@chinedu117 At the moment it looks like you are creating the `users_stations_link` table manually.  Ideally `oso` would create/manage the necessary tables for us.

Could you have a look at their `resource_role_class()` which is a class factory for creating a MixIn that is used by SQLAlchemy to create the required table?

It's described in [this post](https://www.osohq.com/post/introducing-builtin-roles#:~:text=These%20tables%20are%20generated%20by) and also later on in the video below (possibly around 14 minutes in)...
[Adding Structure to a Sea of Chaos: A Principled Approach to Authorization using Python & SQLAlchemy](https://youtu.be/U3YH0tRqh2A)

**Comment by chinedu117** [comment]
> @chinedu117 At the moment it looks like you are creating the `users_stations_link` table manually. Ideally `oso` would create/manage the necessary tables for us.
> 
> Could you have a look at their `resource_role_class()` which is a class factory for creating a MixIn that is used by SQLAlchemy to create the required table?
> 
> It's described in [this post](https://www.osohq.com/post/introducing-builtin-roles#:~:text=These%20tables%20are%20generated%20by) and also later on in the video below (possibly around 14 minutes in)... [Adding Structure to a Sea of Chaos: A Principled Approach to Authorization using Python & SQLAlchemy](https://youtu.be/U3YH0tRqh2A)

Ok. Let me see and get back to you.

**Comment by isedwards** [comment]
@chinedu117 - did you get any further looking into whether `oso` can create/manage the addition tables for us using `resource_role_class()`?

I think that all of our backend Python processes should expect to receive the authorization token (or `request.user` in the case of Django) as their first argument when they are initiated by the user interface. We can then always pass the correct user object to `oso`.

We'll need to make sure this works at least Flask (pygeoapi default) and Django (used by SURFACE CDMS).

BTW - here is a detailed article that Dave found on how we'll be creating reusable backend Python processes using pygeoapi: https://medium.com/geobeyond/create-ogc-processes-in-pygeoapi-11c0f7d3be61

**Comment by chinedu117** [comment]
Please refer to #11

**Comment by chinedu117** [comment]
> @chinedu117 - did you get any further looking into whether `oso` can create/manage the addition tables for us using `resource_role_class()`?
> 
> I think that all of our backend Python processes should expect to receive the authorization token (or `request.user` in the case of Django) as their first argument when they are initiated by the user interface. We can then always pass the correct user object to `oso`.
> 
> We'll need to make sure this works at least Flask (pygeoapi default) and Django (used by SURFACE CDMS).
> 
> BTW - here is a detailed article that Dave found on how we'll be creating reusable backend Python processes using pygeoapi: https://medium.com/geobeyond/create-ogc-processes-in-pygeoapi-11c0f7d3be61

I tried to use the resource_role_class but the function is not available in the sqlalchemy-oso package. Also, it does not create the table automatically as we thought. From the documentation, we would still go on to define it on the models module. 
I finally implemented it by spellingout the relationships on the models module. Please refer to #11  for details.

**Pull request merged**
